### ISSUE TITLE
Sample code not working on Chrome on Android 12

### ISSUE THREAD

**Issue by rjyo** [shuding/cobe#16]
Thanks for the great lib!

The Demo does not work. It looks like the texture is not wrapped around the globe.

- [**Demo** and configurations](https://cobe.vercel.app)

<img src="https://user-images.githubusercontent.com/352545/148146121-ff2c8c7d-908e-4adb-8678-3c8831dcbe2f.png" width="200"/>

The following two work

- Use with React: https://codesandbox.io/s/eager-sky-r2q0g
- Use with vanilla JS: https://codesandbox.io/s/peaceful-gwen-m579y

I tried to put it in a minimum next.js app, the result is the same as the demo on cobe.vercel.app.

https://github.com/rjyo/cobe-test

https://cobe-test.vercel.app/

**Comment by rjyo** [comment]
I found out that the working demos are using 0.4.0. It's only broken in the latest 0.4.1 version with the shader.

**Comment by diegobarroso** [comment]
Indeed, it also works in mobile using version 0.4.0 using Angular. 
https://codesandbox.io/s/broken-darkness-1e97o

**Comment by shuding** [comment]
It was possibly introduced in https://github.com/shuding/cobe/commit/d8b449df43e89c5ecdcaa2f0fa3e42eed3df2dc8, which needs further investigation.

**Comment by farteryhr** [comment]
https://codesandbox.io/s/xvuej?file=/src/App.js

a hacky solution but at least works on my android device.

need to find an elegant and compatible way (among webgl shader implementations) to preserve lowest bits / get reliable warping behavior on overflow for multiplication. `int` is THE pitfall.

**Comment by meerns** [comment]
any update on this ? @shuding

**Comment by shuding** [comment]
Apologize for the delay, I just released v0.4.2 which includes @farteryhr's fix. But unfortunately I don't have an Android device to verify, hope one of you can give it a test :)

**Comment by meerns** [comment]
I tested it and it's working 🎉🚀 @shuding 
Platform: Chrome 99 - Android 12

https://bespoke-mochi-44d1f5.netlify.app/

**Comment by shuding** [comment]
Thanks!
