### ISSUE TITLE
The globe spins slower in safari

### ISSUE THREAD

**Issue by ConsoleTVs** [shuding/cobe#28]
Same configuration, globe spins faster in chrome/firefox than safari

**Comment by ConsoleTVs** [comment]
Turns out is twice as fast for some reason lol;

workaround meanwhile:

```js
// Detect browser
const isSafari = Boolean(
    navigator.vendor &&
      navigator.vendor.indexOf("Apple") > -1 &&
      navigator.userAgent &&
      navigator.userAgent.indexOf("CriOS") == -1 &&
      navigator.userAgent.indexOf("FxiOS") == -1
  );

// The onRender property on the configuration: (just double the value for safari)
state.phi = phi += isSafari ? 0.006 : 0.003;
```

**Comment by shuding** [comment]
That's weird, is it possible that there's some FPS-limiting (`requestAnimationFrame`) configuration in your Safari browser?

**Comment by ConsoleTVs** [comment]
I'll check but I have never tweaked those settings, so they should be the default... Does it work well for you?

**Comment by shuding** [comment]
Yeah it works well for me

**Comment by ConsoleTVs** [comment]
Alright, ill make some tests and see if I come up with anything

**Comment by Mayank-Sh07** [comment]
This could be related to [safari not supporting high refresh rates in older versions](https://www.techradar.com/news/apple-finally-adds-120hz-scrolling-to-safari-on-macbook-pro-but-it-could-be-better). A possible fix for such animation speed differences would be to compute the delta time as suggested [here](https://github.com/shuding/cobe/issues/13). Here's a good read for the same.

[Ensuring Consistent Animation Speeds](https://www.kirupa.com/animations/ensuring_consistent_animation_speeds.htm#)

**Comment by shuding** [comment]
Tracking in #13.
