### ISSUE TITLE
Cobe script fails on the Vercel deployment with Checkly checks

### ISSUE THREAD

**Issue by PrimozRome** [shuding/cobe#33]
Anyone else has problem deploying Cobe to Vercel with Chekly checks (Next.js project)? I am using the example script from the Cobe page. It runs great in local environment, but when I deploy this to Vercel, the deploy is blocked by Checkly. It is failing with "1 Blocking Failures: Prevent these Checks from blocking your deployment by adjusting your"

<img width="1232" alt="Screenshot 2022-08-01 at 10 50 56" src="https://user-images.githubusercontent.com/1180467/182111348-03b04665-6546-465f-95c1-e3df99b26931.png">

If I check the deployment details in Checkly I see there are several console logs reported:

<img width="2031" alt="Screenshot 2022-08-01 at 10 53 42" src="https://user-images.githubusercontent.com/1180467/182111618-54a82204-310f-436b-b626-a3ca3fd7c7f7.png">

Any idea?

**Comment by shuding** [comment]
Hey @PrimozRome, I think the error comes from `experimental-webgl` (https://github.com/vaneenige/phenomenon/blob/master/src/index.ts#L295-L313) being unsupported by the Checkly environment. 

I'll mark this as a bug and fix it in the `cobe` side.
