### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by shuding** [shuding/cobe#4]
On top of #3, let’s create a bunch of useful examples:
- [x] How to use it inside a framework, for example React
- [x] How to manually rotate the globe to a certain location
- [x] How to animate it with 3rd party animation libs

**Comment by 40uf411** [comment]
Can you please provide me with an example where I can use this with react, I could not figure it out.

**Comment by shuding** [comment]
Here is a quick example @40uf411: https://codesandbox.io/s/eager-sky-r2q0g?file=/src/App.js.

**Comment by wheatjs** [comment]
Quickly put together an example using Vue 3 https://stackblitz.com/edit/vitejs-vite-l5a8xk?file=src/App.vue

**Comment by 40uf411** [comment]
@shuding Thank you.

**Comment by shuding** [comment]
@wheatjs Looks great, do you want to open a PR to add it in the README? Thanks!

**Comment by diegobarroso** [comment]
Here an example using Angular
https://codesandbox.io/s/broken-darkness-1e97o

**Comment by mikechibuzor** [comment]
how do I install this in my vue3 project.
it's giving me this error Internal server error: Failed to resolve import "cobe" from "src\App.vue". Does the file exist?

**Comment by iec989** [comment]
RE: _How to manually rotate the globe to a certain location_ , is that even possible right now or does it require an enhancement?

**Comment by shuding** [comment]
Sorry I missed your comment @iec989, but here I got an example: https://cobe.vercel.app/docs/showcases/rotate-to-location
