### ISSUE TITLE
Offset options not working

### ISSUE THREAD

**Issue by zernonia** [shuding/cobe#48]
Based on doc, there's the offset options, but it doesn't seems to work.

Change offset x and y value. Globe stays the same position
https://codesandbox.io/s/dark-hooks-ed5k19?file=/src/App.js

**Comment by shuding** [comment]
The unit is pixel so try something like `[100, 100]` :)

**Comment by zernonia** [comment]
Hmmm.. still not working 
https://codesandbox.io/s/dark-hooks-ed5k19?file=/src/App.js

Also, I was confused by the playground's offsetX & offsetY,
I thought the value should be relative from -1 to 1

![image](https://user-images.githubusercontent.com/59365435/192180455-2a529859-5b29-4f2d-b9fe-1b04507b2c32.png)

**Comment by ZachSaucier** [comment]
It seems to work for me. However, the pixel values seem to be scaled to I had to use larger values than I was first expecting to get the desired results.
