### ISSUE TITLE
Marker onClick or onHover event?

### ISSUE THREAD

**Issue by ronalddas** [shuding/cobe#49]
Hi, is there any way to know when a marker was clicked or hovered over?
I want to display a custom tooltip when a marker is clicked, wondering if this is possible with cobe

**Comment by shuding** [comment]
Sorry, but I don't think that will be possible without significant changes to the project design.

**Comment by ZachSaucier** [comment]
One thought about a work around: Use [`.getImageData()`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData) to detect a color similar to the marker, assuming they're a different color than the rest of the globe. Note that using this isn't very performant so it's probably best not to do every `pointermove` event or something like that.
