### ISSUE TITLE
draggable & rotate-to-location with Vanilla js

### ISSUE THREAD

**Issue by yejigd** [shuding/cobe#51]
Hi, this is the Lib I was looking for!!
Are there any examples of vanillajs code for draggable & rotate-to-location?

I don't know the react, so I'm having a hard time applying it 😢

**Comment by wobsoriano** [comment]
Vanilla Cobe with Drag and Rotate feat: https://stackblitz.com/edit/vitejs-vite-aqcwbr?file=src/globe.ts

**Comment by yejigd** [comment]
@wobsoriano Thank you for the perfect demo!!
I'm really sorry, but if possible, could you post an example of Js about Rotate to Location?

**Comment by yumin-jung** [comment]
Vanilla Cobe with Rotate to Location feat: [Stackblitz](https://stackblitz.com/edit/vanilla-cobe-demo-o5bwcu)
I changed only a few lines of code from @wobsoriano's code.
I hope this helps!!

**Comment by yejigd** [comment]
@yumin-jung Thank you so much. It helped a lot!!
