### ISSUE TITLE
Auto rotate something like blink

### ISSUE THREAD

**Issue by ekaone** [shuding/cobe#58]
At first time i would like to say this is rock Lib, I have used the latest React 18.2.0, but looks like blinking, and try to downgrade to 17.0.2 and running smooth, any ideas for this one. Thanks in advance

**Comment by yumin-jung** [comment]
You can solve it using [react-spring](https://react-spring.dev/).
I think [this page](https://cobe.vercel.app/docs/showcases/draggable-and-rotate) will help you!!

**Comment by shuding** [comment]
I think something in your component is wrong due to React 18's new behavior such as effects will run twice during dev. Maybe you can print more logs to see if this lib is correctly initialized.
